### PR TITLE
fix: iOS virtualbackground color

### LINKED ISSUE #451: Virtual background color inconsistent across iOS and Android
Hi Team, what's the range of the expected red, green and blue values when defining a color for virtual background? I read the docs  and the type definitions but couldn't find the range/bounds. I tried a few different ranges and had inconsistent results between colors on iOS, I tried float value (0-1), percentages (0-100) and 8-bit color (0-255). What's the right way to generate a color using RGB values?

However I wasn't able to get the color to work on Android at all. I used the following snippet and got Red background on iOS but Android only shows white background no matter what I try. Can you tell me what is that I'm doing wrong? (screenshots attached)

```jsx
    await this._engine.enableVideo();
    let color = new Color(1, 0, 0);
    let colorSource = new VirtualBackgroundSource({
      backgroundSourceType: VirtualBackgroundSourceType.Color,
      color: color,
    })
    await this._engine.enableVirtualBackground(true, colorSource);
```
iOS 
IMG_3502
Android 
Screenshot_20211213-211424

### PR DESCRIPTION
**Pull request by EkaanshArora**
Hi @LichKing-2234 this fixes #451

### CODE REVIEW

**Comment by maxxfrazer** [comment]
UIColor is initialised with CGFloat from 0.0 to 1.0, this PR fixes the UIColor initialiser.

Apple Docs:
https://developer.apple.com/documentation/uikit/uicolor/1621925-init

File: ios/RCTAgora/Base/BeanCovertor.swift [hunk 1]
```diff
@@ -123,9 +123,9 @@ func mapToTranscodingUser(_ map: [String: Any]) -> AgoraLiveTranscodingUser {
 
 func mapToColor(_ map: [String: Any]) -> UIColor {
     return UIColor(
-            red: CGFloat((map["red"] as! NSNumber).intValue),
-            green: CGFloat((map["green"] as! NSNumber).intValue),
-            blue: CGFloat((map["blue"] as! NSNumber).intValue),
+            red: (map["red"] as! CGFloat) / 255,
```
Comment (LichKing-2234) [inline ios/RCTAgora/Base/BeanCovertor.swift:126]: Can int value cast to CGFloat?
I think it should cast to NSNumber.
`CGFloat((map["red"] as! NSNumber).floatValue / 255)`

File: ios/RCTAgora/Base/BeanCovertor.swift [hunk 2]
```diff
@@ -123,9 +123,9 @@ func mapToTranscodingUser(_ map: [String: Any]) -> AgoraLiveTranscodingUser {
...
+            green: (map["green"] as! CGFloat) / 255,
```
Comment (LichKing-2234) [inline ios/RCTAgora/Base/BeanCovertor.swift:127]: CGFloat((map["green"] as! NSNumber).floatValue / 255)

File: ios/RCTAgora/Base/BeanCovertor.swift [hunk 3]
```diff
@@ -123,9 +123,9 @@ func mapToTranscodingUser(_ map: [String: Any]) -> AgoraLiveTranscodingUser {
...
+            blue: (map["blue"] as! CGFloat) / 255,
```
Comment (LichKing-2234) [inline ios/RCTAgora/Base/BeanCovertor.swift:128]: CGFloat((map["blue"] as! NSNumber).floatValue / 255)

File: src/common/Classes.ts [hunk 4]
```diff
@@ -481,22 +481,27 @@ export class TranscodingUser {
...
+   * Green value (0 - 255)
    */
   green: number;
   /**
-   * Blue.
+   * Blue value (0 - 255)
    */
   blue: number;
-
+  /**
```
Comment (LichKing-2234) [inline src/common/Classes.ts:500]: Pls insert new line.

**Review by LichKing-2234 — CHANGES_REQUESTED** [review]

File: ios/RCTAgora/Base/BeanCovertor.swift (hunk 1 above)
Comment (maxxfrazer) [reply ios/RCTAgora/Base/BeanCovertor.swift:126]: NSNumber and CGFloat are interchangeable through typecasting since swift 2

for example this is valid:

```swift
let c1 = CGFloat(12.3)
let num = c1 as NSNumber
let c2 = num as CGFloat
```

Comment (EkaanshArora) [reply ios/RCTAgora/Base/BeanCovertor.swift:126]: I tried several different combinations of Color values and it all works as expected.

Comment (LichKing-2234) [reply ios/RCTAgora/Base/BeanCovertor.swift:126]: have you tried int value? giving the int value at js layer

Comment (maxxfrazer) [reply ios/RCTAgora/Base/BeanCovertor.swift:126]: @LichKing-2234 any thoughts on this?

**Review by LichKing-2234 — APPROVED** [review]
